BEGIN {
	y = 1;

	printf("/* generated by makefont.awk */\n");
	printf("EXTERN const uint8_t font[]\n");
	printf("#if defined(DEF_GLOBAL)\n")
	printf("= {\n");
}

{
	if($0 != "") {
		if(substr($0, 1, 1) == "#")	x[0] += y;
		if(substr($0, 2, 1) == "#")	x[1] += y;
		if(substr($0, 3, 1) == "#")	x[2] += y;
		if(substr($0, 4, 1) == "#")	x[3] += y;
		if(substr($0, 5, 1) == "#")	x[4] += y;
		if(substr($0, 6, 1) == "#")	x[5] += y;

		if(y != 64)
			y *= 2;
		else {
			printf("	0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x,\n", x[0], x[1], x[2], x[3], x[4]);
			x[4] = x[3] = x[2] = x[1] = x[0] = 0;
			y = 1;
		}
	}
}

END {
	printf("}\n");
	printf("#endif\n");
	printf(";\n");
}
