daa.txt: daa.c
	gcc -o daa daa.c
	./daa > daa.txt
parity.txt:
	gcc -o parity parity.c
	./parity > parity.txt
clean:
	rm -f daa
	rm -f daa.exe
	rm -f parity
	rm -f parity.exe
	rm -f daa.txt
	rm -f parity.txt
